### ISSUE TITLE
NullPointerExceptions appears instead of Parse Errors

### ISSUE THREAD

**Issue by favu100** [bendisposto/ltl-pattern-parser#1]
Caused by: java.lang.NullPointerException: null
	at de.prob.ltl.parser.semantic.PatternDefinition.determineTokenAndName(PatternDefinition.java:50)
	at de.prob.ltl.parser.semantic.PatternDefinition.<init>(PatternDefinition.java:37)
	at de.prob.ltl.parser.semantic.SemanticCheck.collectAndCheckPatternDefinitions(SemanticCheck.java:43)
	at de.prob.ltl.parser.semantic.SemanticCheck.check(SemanticCheck.java:35)
	at de.prob.ltl.parser.LtlParser.parsePatternDefinition(LtlParser.java:147)
	at de.prob.ltl.parser.pattern.Pattern.updateDefinitions(Pattern.java:37)

appears if the code of a LTLPattern or LTLFormula is "def "

**Comment by favu100** [comment]
Caused by: java.lang.NullPointerException: null
	at de.prob.ltl.parser.semantic.AbstractSemanticObject.createVariable(AbstractSemanticObject.java:29)
	at de.prob.ltl.parser.semantic.VariableDefinition.determineVariableInfo(VariableDefinition.java:36)
	at de.prob.ltl.parser.semantic.VariableDefinition.<init>(VariableDefinition.java:20)
	at de.prob.ltl.parser.semantic.Body.checkContext(Body.java:33)
	at de.prob.ltl.parser.semantic.Body.<init>(Body.java:21)
	at de.prob.ltl.parser.semantic.SemanticCheck.check(SemanticCheck.java:28)
	at de.prob.ltl.parser.LtlParser.parse(LtlParser.java:136)

appears if the code of a LTLFormula contains a keyword for variable declaration but no variable is declared e.g. "var ", "num ", "seq "

**Comment by favu100** [comment]
Caused by: java.lang.NullPointerException: null	
at de.prob.ltl.parser.semantic.Loop.checkLoopBody(Loop.java:68)
	at de.prob.ltl.parser.semantic.Loop.<init>(Loop.java:42)
	at de.prob.ltl.parser.semantic.Body.checkContext(Body.java:37)
	at de.prob.ltl.parser.semantic.Body.<init>(Body.java:21)
	at de.prob.ltl.parser.semantic.SemanticCheck.check(SemanticCheck.java:28)
	at de.prob.ltl.parser.LtlParser.parse(LtlParser.java:136)

appears if the code of a LTLFormula has a parse error in a loop e.g. "count " or

"var j = 0
count i:1 up to 10:
	true
end"
